export * from "discord.js"
export * from "./app/database"
export * from "./app/listener"
export * from "./app/command"
export * from "./app/utils"

export * as Discord from "discord.js"
export * as database from "./app/database"
export * as listener from "./app/listener"
export * as command from "./app/command"
export * as utils from "./app/utils"
